# タイムアウトは 10 分に設定
timeout: "600s"

steps:
  # gcloud CLI を利用した情報表示と Docker push 用認証
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    id: 'gcloud-setup'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          echo "==> Running gcloud info..."
          gcloud info
          echo "==> Configuring Docker for us-central1-docker.pkg.dev..."
          gcloud auth configure-docker us-central1-docker.pkg.dev

  # Node.js を利用したビルド・デプロイ処理（ブランチによって処理を分岐）
  - name: 'node:22.13.1'
    id: 'build-and-deploy-advena-frontend'
    entrypoint: 'bash'
    # シークレットをこのステップに注入
    secretEnv:
      - FRONTEND_WEB_DOTENV_PRIVATE_KEY_DEV
      - FRONTEND_WEB_DOTENV_PRIVATE_KEY_PRD
    args:
      - '-c'
      - |
          set -eo pipefail

          echo "==> Installing mise..."
          curl https://mise.run | sh
          # PATH の更新
          export PATH="$$HOME/.local/share/mise/bin:$$HOME/.local/share/mise/shims:$$PATH"

          echo "==> Installing pnpm (v9)..."
          npm install -g pnpm@9

          echo "==> Changing directory to frontend/web..."
          ls

          echo "==> Installing dependencies with mise exec..."
          mise exec -- pnpm install

          echo "==> Current branch: $BRANCH_NAME"
          if [[ "$BRANCH_NAME" == "develop" ]]; then
              echo "==> Running build for develop"
              # Secret Manager で注入した値を環境変数に設定
              export DOTENV_PRIVATE_KEY_DEV="$$FRONTEND_WEB_DOTENV_PRIVATE_KEY_DEV"
              mise run fe:build:dev
              echo "==> Running push for develop"
              mise run fe:push:dev
          elif [[ "$BRANCH_NAME" == "main" ]]; then
              echo "==> Running build for main"
              export DOTENV_PRIVATE_KEY_PRD="$$FRONTEND_WEB_DOTENV_PRIVATE_KEY_PRD"
              mise run fe:build:prd
              echo "==> Running push for main"
              mise run fe:push:prd
          else
              echo "==> Branch '$BRANCH_NAME' does not trigger build/push."
          fi

availableSecrets:
  secretManager:
    # dotenvx .env.keys で管理しているシークレットを取得
    # projects/YOUR_PROJECT_ID/secrets/YOUR_SECRET_NAME/versions/latest
    - versionName: "projects/38358387786/secrets/advena_frontend_DOTENV_PRIVATE_KEY_DEV/versions/latest"
      env: "FRONTEND_WEB_DOTENV_PRIVATE_KEY_DEV"
    - versionName: "projects/38358387786/secrets/advena_frontend_DOTENV_PRIVATE_KEY_PRD/versions/latest"
      env: "FRONTEND_WEB_DOTENV_PRIVATE_KEY_PRD"
