name: Format
on: [push, pull_request]

jobs:
  frontend:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use mise
      run: |
        curl https://mise.run | sh
        echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
        echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'pnpm'
        cache-dependency-path: ./frontend/web/pnpm-lock.yaml

    - name: Install dependencies
      run: mise exec -- pnpm install
      working-directory: ./frontend/web
    - name: Run format
      run: |
        mise run fe:format
        # フォーマット後の差分を確認
        git diff --exit-code
      working-directory: ./frontend/web

  backend:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use mise
      run: |
        curl https://mise.run | sh
        echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
        echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: mise exec -- uv sync --all-extras --dev
      working-directory: ./backend/genai
    - name: Run format
      run: | 
        mise run be:format
        # フォーマット後の差分を確認
        git diff --exit-code
      working-directory: ./backend/genai