name: Format

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-format
  cancel-in-progress: true

jobs:
  frontend:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'
          cache: 'npm'
          cache-dependency-path: ./frontend/web/pnpm-lock.yaml

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: mise exec -- pnpm install
        working-directory: ./frontend/web

      - name: Run format
        run: |
          mise run fe:format
          git diff --exit-code
        working-directory: ./frontend/web

      - name: Show formatting diff on failure
        if: failure()
        run: git diff
        working-directory: ./frontend/web

  backend:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: ./backend/genai/uv.lock

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: mise exec -- uv sync --frozen
        working-directory: ./backend/genai

      - name: Run format
        run: |
          mise run be:format
          git diff --exit-code
        working-directory: ./backend/genai

      - name: Show formatting diff on failure
        if: failure()
        run: git diff
        working-directory: ./backend/genai
