name: Test

on: 
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          cache-dependency-path: ./frontend/web/pnpm-lock.yaml

      - name: Install dependencies
        run: mise exec -- pnpm install
        working-directory: ./frontend/web

      - name: Run test
        run: |
          set -eo pipefail
          mise run fe:test
        working-directory: ./frontend/web

  backend:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Use mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'advena-dev'
          workload_identity_provider: 'projects/38358387786/locations/global/workloadIdentityPools/github/providers/my-repo'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: ./backend/genai/uv.lock

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: mise exec -- uv sync --frozen
        working-directory: ./backend/genai

      - name: Run test
        run: |
          set -eo pipefail
          mise run be:test
        working-directory: ./backend/genai
        env:
          CI: 'true'
